# Generated by Django 5.2.3 on 2025-12-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
        ),
    ]
