# Generated by Django 5.2.3 on 2026-01-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_status_order'),
        ('pos', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.status_order', verbose_name='حالة الطلب'),
        ),
    ]
