# Generated by Django 5.2.3 on 2026-01-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_ingredientcategory_unit_choices'),
        ('pos', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='اسم العميل')),
                ('mobil', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000, verbose_name='عنوان العميل')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الحالية')),
                ('min_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حد الطلب (الحد الأدنى)')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.ingredientcategory', verbose_name='الفئة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.unit_choices', verbose_name='الوحدة')),
            ],
        ),
    ]
